### ISSUE TITLE
Update from node 12 to node 16

### ISSUE THREAD

**Issue by apupier** [stringbean/docker-healthcheck-action#1]
Given that Node.js 12 actions are deprecated, it would be nice to upgrade to Node 16

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

https://github.com/stringbean/docker-healthcheck-action/blob/5cd950cd372298951dd153e980462980d4816821/action.yml#L31

**Comment by stringbean** [comment]
Fixed in v2.0.0
